
kon = parameters(1);
koff = 1000;%parameters(2);
kesc = parameters(3);
kproc = parameters(4);
kin =  1000*parameters(5);
kout = parameters(6);

S = [1 0 0;...
    -1 0 0;...
    0 1 0;...
    0 -1 0;...
    0 -1 1;...
    0  0 -1]';

w = @(x,y,z)[kon*(1-x),...
    koff*x,...
    kin*x,...
    kout*y,...
    kesc*y,...
    kproc*z];

t_Array = linspace(0,200,201);
f = @(x,y,z)[-x,-y,-z,x,y,z];     % Truncation shape function -- the first four MUST be [-x -y x y]
b = [0 0 0 1 3 10 ];                       % Truncation boundaries
eps_max = 0.01;

Run_3_State_FSP_BEM(S,w,t_Array,f,b,eps_max)
    

